export const APP_FEATURES = [ 
    {
        id: "01",
        title: "Tailored Just for You",
        description: 
        "Get interview questions and model answers based on your role, experience, and specific focus across areas"
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description: 
            "Expand answers only when you're ready. Dive Deeper into any concept instantly with AI-powered detailed"
    },    
    {
        id: "03",
        title: "Capture Your Insights",
        description: 
           "Add personal notes to any question and pin interest ones to the top - making your learning more organised"
    }, 
    {
        id: "04",
        title: 'Understand the "why" Behind Answers',
        description: 
            "Beyond just answers - unlock detailed concept explanations generated by AI, helping you truly master each concepts"
    }, 
    {
        id: "05",
        title: "Save, Organize and Revisit",
        description: 
            "Easily save your interview sets, organize them neatly in your dashboard, and pick up your prepration from Beginning"
    }, 
]